.PHONY: all clean context

TOP_DIR = $(shell pwd)

CC := "aarch64-none-elf-gcc"
LIBGCC := $(shell $(CC) -print-libgcc-file-name)
#$(info LIBGCC:$(LIBGCC))

default:all

all:context env_prepare
	@gn gen out && cd out && ninja -v

$(TOP_DIR)/build/config/env.gni:
	@echo "generate build/config/compiler_toolchain.gni"
	@echo "# This file is autogenerated! Do not edit." > $@
ifneq ($(LIBGCC),)
	@echo "env_libs = \"$(LIBGCC)\"" >> $@
endif

$(TOP_DIR)/app/musl-1.2.3/out/lib/libc.a:
	@cd $(TOP_DIR)/app/musl-1.2.3 && ./configure --prefix=./out CROSS_COMPILE=aarch64-none-elf- && make && make install

env_prepare:$(TOP_DIR)/build/config/env.gni $(TOP_DIR)/app/musl-1.2.3/out/lib/libc.a
	@echo "General env prepare..."

clean:
	@echo "clean..."
	@cd out && ninja -t clean
	@rm -rf $(TOP_DIR)/build/config/env.gni
	@rm -rf $(TOP_DIR)/os/linker.lds

$(TOP_DIR)/os/linker.lds:$(TOP_DIR)/os/include/chinos/config.h
	@echo "generate os/linker.lds"
	@$(CC) -E -x c -P -I $(TOP_DIR)/os/include -o $@ $(TOP_DIR)/os/linker.lds_pp

context:$(TOP_DIR)/os/linker.lds
	@echo "General contex..."
