.PHONY: all clean

TOP_DIR = $(shell pwd)

CC := "aarch64-none-elf-gcc"
LIBGCC := $(shell $(CC) -print-libgcc-file-name)
$(info LIBGCC:$(LIBGCC))

default:all

all:env_prepare
	@gn gen out && cd out && ninja -v

$(TOP_DIR)/build/config/env.gni:
	@echo "generate build/config/compiler_toolchain.gni"
	@echo "# This file is autogenerated! Do not edit." > $@
ifneq ($(LIBGCC),)
	@echo "env_libs = \"$(LIBGCC)\"" >> $@
endif

$(TOP_DIR)/app/musl-1.2.3/out/lib/libc.a:
	@cd $(TOP_DIR)/app/musl-1.2.3 && ./configure --prefix=./out CROSS_COMPILE=aarch64-none-elf- && make && make install

env_prepare:$(TOP_DIR)/build/config/env.gni $(TOP_DIR)/app/musl-1.2.3/out/lib/libc.a
	@echo "General env prepare..."

clean:
	@echo "clean..."
	@cd out && ninja -t clean
	@rm $(TOP_DIR)/build/config/env.gni