#!/bin/bash

# Load by elf
qemu-system-aarch64 -M virt,gic-version=3,virtualization=on -cpu cortex-a53 -m 1024 -nographic -kernel ./out/image/os.elf

# Load by binary
# need configs:
#   CONFIG_KERNEL_LOAD_ADDR = 0x40080000
# qemu-system-aarch64 -M virt,gic-version=3,virtualization=on -cpu cortex-a53 -m 1024 -nographic -kernel ./out/image/os.bin
